### PR TITLE
yts.to -> yts.ag

### LINKED ISSUE #4: YTS / YIFY is currently down.
If you've come here wondering why the YIFY gem isn't working / returning any results, it's because the YTS API has been down for a few weeks. Once [this page](https://popcorntime.statuspage.io/) has YTS with a green status, everything should be back to normal.

### PR DESCRIPTION
**Pull request by alesya-h**
Should fix #4

### CODE REVIEW

**Comment by jonlunsford** [comment]
Awesome! Thanks for the PR. It looks like you ran everything against the live api as well? Were the cassettes re generated? Or edited by hand? My concern is that the fixtures are out of date with the current state of the api.

**Comment by alesya-h** [comment]
Nope, I didn't. It was just `find -type f|xargs -I {} sed -i 's/yts.to/yts.ag/g' {}` inside lib and spec. I tried to run specs, but got some weird JSON parse errors, complaining about things like `<USER_ID>` inside json.

**Comment by jonlunsford** [comment]
Ah ok, I’ll re run the tests to make sure the api endpoints are still producing the same output.

-- 
Jon Lunsford
Web Developer
Capture The Castle
jon@capturethecastle.net
(206) 953-3666

**Comment by jonlunsford** [comment]
The API is still in flux, I've merged this into the [working-endpoints](https://github.com/jonlunsford/yify/tree/working-endpoints) branch for now. Work will continue there as endpoints become functional. Currently only `list_movies`, `movie_details`, and `movie_suggestions` work.

**Pull request closed without merging**
